//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosplayWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerModel
    {
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<long> CustomerProfilePic { get; set; }
        public string CustomerPassword { get; set; }
    }
}
